//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Terminals.Data.DB
{
    using System;
    using System.Collections.Generic;
    
    internal partial class DbFavorite
    {
        public string Name { get; set; }
        public int Port { get; set; }
        public string ServerName { get; set; }
        public bool NewWindow { get; set; }
        public string DesktopShare { get; set; }
        public string Notes { get; set; }
        public byte[] IconData { get; set; }
        public byte[] Version { get; set; }
    
        public virtual DbBeforeConnectExecute ExecuteBeforeConnect { get; set; }
        public virtual DbDisplayOptions Display { get; set; }
        public virtual DbSecurityOptions Security { get; set; }
        public virtual ICollection<DbGroup> Groups { get; set; }
    }
}
