//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Terminals.Data.DB
{
    using System;
    using System.Collections.Generic;
    
    internal partial class DbGroup
    {
        public DbGroup()
        {
            this.ChildGroups = new HashSet<DbGroup>();
            this.Favorites = new HashSet<DbFavorite>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<DbGroup> ChildGroups { get; set; }
        public virtual DbGroup ParentGroup { get; set; }
        public virtual ICollection<DbFavorite> Favorites { get; set; }
    }
}
