//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Terminals.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedValues {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedValues() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Terminals.Localization.LocalizedValues", typeof(LocalizedValues).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Current Connection To.
        /// </summary>
        internal static string AddCurrentConnectionTo {
            get {
                return ResourceManager.GetString("AddCurrentConnectionTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alphabetical.
        /// </summary>
        internal static string Alphabetical {
            get {
                return ResourceManager.GetString("Alphabetical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to disconnect from the active terminal?.
        /// </summary>
        internal static string Areyousurethatyouwanttodisconnectfromtheactiveterminal {
            get {
                return ResourceManager.GetString("Areyousurethatyouwanttodisconnectfromtheactiveterminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to connect to all {0} terminal(s)?.
        /// </summary>
        internal static string Areyousureyouwanttoconnecttoalltheseterminals {
            get {
                return ResourceManager.GetString("Areyousureyouwanttoconnecttoalltheseterminals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to log this session off?.
        /// </summary>
        internal static string Areyousureyouwanttologthissessionoff {
            get {
                return ResourceManager.GetString("Areyousureyouwanttologthissessionoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reboot this machine?.
        /// </summary>
        internal static string Areyousureyouwanttorebootthismachine {
            get {
                return ResourceManager.GetString("Areyousureyouwanttorebootthismachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to shut this machine off?.
        /// </summary>
        internal static string Areyousureyouwanttoshutthismachineoff {
            get {
                return ResourceManager.GetString("Areyousureyouwanttoshutthismachineoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Manager.
        /// </summary>
        internal static string CaptureManager {
            get {
                return ResourceManager.GetString("CaptureManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Terminal Screen.
        /// </summary>
        internal static string CaptureTerminalScreen {
            get {
                return ResourceManager.GetString("CaptureTerminalScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to Show or Hide Terminals Main Window.
        /// </summary>
        internal static string ClicktoShoworHideTerminalsMainWindow {
            get {
                return ResourceManager.GetString("ClicktoShoworHideTerminalsMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer.
        /// </summary>
        internal static string Computer {
            get {
                return ResourceManager.GetString("Computer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer Management (MMC).
        /// </summary>
        internal static string ComputerManagementMMC {
            get {
                return ResourceManager.GetString("ComputerManagementMMC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Multiple Items.
        /// </summary>
        internal static string ConfirmCaptionDeleteMultipleItems {
            get {
                return ResourceManager.GetString("ConfirmCaptionDeleteMultipleItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Folder.
        /// </summary>
        internal static string ConfirmCaptionDeleteSingleFolder {
            get {
                return ResourceManager.GetString("ConfirmCaptionDeleteSingleFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Item.
        /// </summary>
        internal static string ConfirmCaptionDeleteSingleItem {
            get {
                return ResourceManager.GetString("ConfirmCaptionDeleteSingleItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete these {0} files?.
        /// </summary>
        internal static string ConfirmDeleteMultipleFiles {
            get {
                return ResourceManager.GetString("ConfirmDeleteMultipleFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this file?.
        /// </summary>
        internal static string ConfirmDeleteSingleFile {
            get {
                return ResourceManager.GetString("ConfirmDeleteSingleFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this folder?.
        /// </summary>
        internal static string ConfirmDeleteSingleFolder {
            get {
                return ResourceManager.GetString("ConfirmDeleteSingleFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Information.
        /// </summary>
        internal static string ConnectionInformation {
            get {
                return ResourceManager.GetString("ConnectionInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect To.
        /// </summary>
        internal static string ConnectTo {
            get {
                return ResourceManager.GetString("ConnectTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect To All.
        /// </summary>
        internal static string ConnectToAll {
            get {
                return ResourceManager.GetString("ConnectToAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect To Console.
        /// </summary>
        internal static string ConnectToConsole {
            get {
                return ResourceManager.GetString("ConnectToConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect To Server.
        /// </summary>
        internal static string Connecttoserver {
            get {
                return ResourceManager.GetString("Connecttoserver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Panel.
        /// </summary>
        internal static string ControlPanel {
            get {
                return ResourceManager.GetString("ControlPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Group From Active Connections.
        /// </summary>
        internal static string CreateGroupFromActiveConnections {
            get {
                return ResourceManager.GetString("CreateGroupFromActiveConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials Manager.
        /// </summary>
        internal static string CredentialsManager {
            get {
                return ResourceManager.GetString("CredentialsManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        internal static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect From Server.
        /// </summary>
        internal static string DisconnectFromServer {
            get {
                return ResourceManager.GetString("DisconnectFromServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNS.
        /// </summary>
        internal static string DNS {
            get {
                return ResourceManager.GetString("DNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Terminals.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        internal static string Favorites {
            get {
                return ResourceManager.GetString("Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Screen.
        /// </summary>
        internal static string FullScreen {
            get {
                return ResourceManager.GetString("FullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grab Input.
        /// </summary>
        internal static string GrabInput {
            get {
                return ResourceManager.GetString("GrabInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        internal static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Hide / Show.
        /// </summary>
        internal static string HideShow {
            get {
                return ResourceManager.GetString("HideShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to change the toolbars, you must first unlock them..
        /// </summary>
        internal static string Inordertochangethetoolbarsyoumustfirstunlockthem {
            get {
                return ResourceManager.GetString("Inordertochangethetoolbarsyoumustfirstunlockthem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Toolbars.
        /// </summary>
        internal static string LockToolbars {
            get {
                return ResourceManager.GetString("LockToolbars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logoff.
        /// </summary>
        internal static string Logoff {
            get {
                return ResourceManager.GetString("Logoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organize Favorites.
        /// </summary>
        internal static string ManageConnections {
            get {
                return ResourceManager.GetString("ManageConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        internal static string Management {
            get {
                return ResourceManager.GetString("Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Toolbar.
        /// </summary>
        internal static string ManageToolbar {
            get {
                return ResourceManager.GetString("ManageToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message from your Administrator.
        /// </summary>
        internal static string MessagefromyourAdministrator {
            get {
                return ResourceManager.GetString("MessagefromyourAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        internal static string Minimize {
            get {
                return ResourceManager.GetString("Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Networking Tools.
        /// </summary>
        internal static string NetworkingTools {
            get {
                return ResourceManager.GetString("NetworkingTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Connection.
        /// </summary>
        internal static string NewConnection {
            get {
                return ResourceManager.GetString("NewConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Release Available.
        /// </summary>
        internal static string NewReleaseAvailable {
            get {
                return ResourceManager.GetString("NewReleaseAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organize Favorites.
        /// </summary>
        internal static string OrganizeFavorites {
            get {
                return ResourceManager.GetString("OrganizeFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organize Favorites Toolbar.
        /// </summary>
        internal static string OrganizeFavoritesToolbar {
            get {
                return ResourceManager.GetString("OrganizeFavoritesToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organize Groups.
        /// </summary>
        internal static string OrganizeGroups {
            get {
                return ResourceManager.GetString("OrganizeGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organize Shortcuts.
        /// </summary>
        internal static string OrganizeShortcuts {
            get {
                return ResourceManager.GetString("OrganizeShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organize Shortucts.
        /// </summary>
        internal static string OrganizeShortucts {
            get {
                return ResourceManager.GetString("OrganizeShortucts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping.
        /// </summary>
        internal static string Ping {
            get {
                return ResourceManager.GetString("Ping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the message to send:.
        /// </summary>
        internal static string Pleaseenterthemessagetosend {
            get {
                return ResourceManager.GetString("Pleaseenterthemessagetosend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        internal static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Connect.
        /// </summary>
        internal static string QuickConnect {
            get {
                return ResourceManager.GetString("QuickConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot.
        /// </summary>
        internal static string Reboot {
            get {
                return ResourceManager.GetString("Reboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuild Shortcuts.
        /// </summary>
        internal static string RebuildShortcuts {
            get {
                return ResourceManager.GetString("RebuildShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuild Tags Index.
        /// </summary>
        internal static string RebuildTagsIndex {
            get {
                return ResourceManager.GetString("RebuildTagsIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuild Toolbars.
        /// </summary>
        internal static string RebuildToolbars {
            get {
                return ResourceManager.GetString("RebuildToolbars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        internal static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Screen.
        /// </summary>
        internal static string RestoreScreen {
            get {
                return ResourceManager.GetString("RestoreScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Capture Manager.
        /// </summary>
        internal static string ScreenCaptureManager {
            get {
                return ResourceManager.GetString("ScreenCaptureManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send ALT-F4 Keys.
        /// </summary>
        internal static string SendALTF4Keys {
            get {
                return ResourceManager.GetString("SendALTF4Keys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send ALT Key.
        /// </summary>
        internal static string SendALTKey {
            get {
                return ResourceManager.GetString("SendALTKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send CTRL ESC Keys.
        /// </summary>
        internal static string SendCTRLESCKeys {
            get {
                return ResourceManager.GetString("SendCTRLESCKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send CTRL Key.
        /// </summary>
        internal static string SendCTRLKey {
            get {
                return ResourceManager.GetString("SendCTRLKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Message.
        /// </summary>
        internal static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent CTRL ALT DEL Keys.
        /// </summary>
        internal static string SentCTRLALTDELKeys {
            get {
                return ResourceManager.GetString("SentCTRLALTDELKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        internal static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sessions.
        /// </summary>
        internal static string Sessions {
            get {
                return ResourceManager.GetString("Sessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcuts.
        /// </summary>
        internal static string Shortcuts {
            get {
                return ResourceManager.GetString("Shortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide Menu.
        /// </summary>
        internal static string ShowMenu {
            get {
                return ResourceManager.GetString("ShowMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown.
        /// </summary>
        internal static string Shutdown {
            get {
                return ResourceManager.GetString("Shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, Terminals was unable to connect to the remote machine.  Try again, or check the log for more information..
        /// </summary>
        internal static string SorryTerminalswasunabletoconnecttotheremotemachineTryagainorcheckthelogformoreinformation {
            get {
                return ResourceManager.GetString("SorryTerminalswasunabletoconnecttotheremotemachineTryagainorcheckthelogformoreinf" +
                        "ormation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Commands.
        /// </summary>
        internal static string SpecialCommands {
            get {
                return ResourceManager.GetString("SpecialCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Toolbar.
        /// </summary>
        internal static string StandardToolbar {
            get {
                return ResourceManager.GetString("StandardToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        internal static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal.
        /// </summary>
        internal static string Terminal {
            get {
                return ResourceManager.GetString("Terminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminals.
        /// </summary>
        internal static string Terminals {
            get {
                return ResourceManager.GetString("Terminals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal Server.
        /// </summary>
        internal static string TerminalServer {
            get {
                return ResourceManager.GetString("TerminalServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminals News.
        /// </summary>
        internal static string TerminalsNews {
            get {
                return ResourceManager.GetString("TerminalsNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trace Route.
        /// </summary>
        internal static string TraceRoute {
            get {
                return ResourceManager.GetString("TraceRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TS Admin.
        /// </summary>
        internal static string TSAdmin {
            get {
                return ResourceManager.GetString("TSAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnTagged.
        /// </summary>
        internal static string UnTagged {
            get {
                return ResourceManager.GetString("UnTagged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View in new Window.
        /// </summary>
        internal static string ViewinnewWindow {
            get {
                return ResourceManager.GetString("ViewinnewWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VMRC: Switch to Administrator View.
        /// </summary>
        internal static string VMRCSwitchtoAdministratorView {
            get {
                return ResourceManager.GetString("VMRCSwitchtoAdministratorView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VMRC: View Only Mode.
        /// </summary>
        internal static string VMRCViewOnlyMode {
            get {
                return ResourceManager.GetString("VMRCViewOnlyMode", resourceCulture);
            }
        }
    }
}
