//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Terminals.Data.DB
{
    using System;
    using System.Collections.Generic;
    
    internal partial class DbCredentialBase
    {
        public DbCredentialBase()
        {
            this.Security = new HashSet<DbSecurityOptions>();
        }
    
        public int Id { get; set; }
        public string EncryptedUserName { get; set; }
        public string EncryptedDomain { get; set; }
        public string EncryptedPassword { get; set; }
    
        public virtual ICollection<DbSecurityOptions> Security { get; set; }
    }
}
