//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Terminals.Data.DB
{
    using System;
    using System.Collections.Generic;
    
    internal partial class DbBeforeConnectExecute
    {
        public int FavoriteId { get; set; }
        public bool Execute { get; set; }
        public string Command { get; set; }
        public string CommandArguments { get; set; }
        public string InitialDirectory { get; set; }
        public bool WaitForExit { get; set; }
    
        public virtual DbFavorite Favorite { get; set; }
    }
}
