name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # because of legacy dotnet 4.8
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3
      - name: Setup-msbuild
        uses: microsoft/setup-msbuild@v1.1
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.1.1
      - name: Build solution
        shell: pwsh
        working-directory: .\Build
        run: .\build.ps1
      - name: Setup VSTest
        uses: darenm/Setup-VSTest@v1.2
      - name: Install a SQL Server suite of tools
        uses: potatoqualitee/mssqlsuite@v1.7
        with:
          install: localdb
          show-log: true
      - name: Test
        run: vstest.console.exe /logger:"trx;LogFileName=test_results.trx" Build\Output\Release\net4.8\Tests.dll
        continue-on-error: true
      - name: Test Report
        uses: dorny/test-reporter@v1.6.0
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: MSTests
          path: TestResults/test_results.trx
          fail-on-error: 'false' # sincet the localdb tests configuration
          reporter: dotnet-trx 